version: '3.9'

services:
  sqlserver-auth:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-auth-data:/var/opt/mssql

  sqlserver-account:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-account-data:/var/opt/mssql

  sqlserver-appointment:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1435:1433"
    volumes:
      - sqlserver-appointment-data:/var/opt/mssql
 
  sqlserver-categories:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1436:1433"
    volumes:
      - sqlserver-categories-data:/var/opt/mssql

  sqlserver-doctor:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1437:1433"
    volumes:
      - sqlserver-doctor-data:/var/opt/mssql
 
  sqlserver-documents:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1445:1433"
    volumes:
      - sqlserver-documents-data:/var/opt/mssql

  sqlserver-office:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1438:1433"
    volumes:
      - sqlserver-office-data:/var/opt/mssql

  sqlserver-patient:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1439:1433"
    volumes:
      - sqlserver-patient-data:/var/opt/mssql

  sqlserver-photo:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1440:1433"
    volumes:
      - sqlserver-photo-data:/var/opt/mssql

  sqlserver-receptionist:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1441:1433"
    volumes:
      - sqlserver-receptionist-data:/var/opt/mssql

  # sqlserver-results:
  #   image:  mcr.microsoft.com/mssql/server:2022-latest
  #   environment:
  #     SA_PASSWORD: "MyPassword12345!"
  #     ACCEPT_EULA: "Y"
  #     MSSQL_PID: "Express"
  #   ports:
  #     - "1442:1433"
  #   volumes:
  #     - sqlserver-results-data:/var/opt/mssql
      
  sqlserver-services:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1443:1433"
    volumes:
      - sqlserver-services-data:/var/opt/mssql
  
  sqlserver-specialization:
    image:  mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "MyPassword12345!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1444:1433"
    volumes:
      - sqlserver-specialization-data:/var/opt/mssql

  auth-service:
    build: 
      context: .
      dockerfile: services/AuthService/Dockerfile
    ports:
      - "5184:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_AuthDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - Jwt__Key=q5hTNs7DFIYcx7PbIae6BLInYyFj+zBPwRwQnS5jQbF7H7kncV0X+ZcT6LJvzzQzI5ue/4CkXyAQ3jv4W5EyEw==
      - Jwt__Issuer=InnoClinic.AuthService
      - Jwt__Audience=InnoClinic.Services
    depends_on:
      - sqlserver-auth

  account-service:
    build: 
      context: .
      dockerfile: services/AccountService/Dockerfile
    ports:
      - "5185:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_AccountDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-account


  appointment-service:
    build: 
      context: .
      dockerfile: services/AppointmentsService/Dockerfile
    ports:
      - "5186:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_AppointmentDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-appointment

  categories-service:
    build: 
      context: .
      dockerfile: services/CategoriesService/Dockerfile
    ports:
      - "5187:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_CategoryDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-categories

  doctor-service:
    build: 
      context: .
      dockerfile: services/DoctorService/Dockerfile
    ports:
      - "5188:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_DoctorDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-doctor

  documents-service:
    build: 
      context: .
      dockerfile: services/DocumentsService/Dockerfile
    ports:
      - "5196:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_DocumentDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-documents

  office-service:
    build: 
      context: .
      dockerfile: services/OfficesService/Dockerfile
    ports:
      - "5189:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_OfficeDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-office

  patient-service:
    build: 
      context: .
      dockerfile: services/PatientService/Dockerfile
    ports:
      - "5190:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_PatientDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-patient

  photo-service:
    build: 
      context: .
      dockerfile: services/PhotoService/Dockerfile
    ports:
      - "5191:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_PhotoDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-photo

  receptionist-service:
    build: 
      context: .
      dockerfile: services/ReceptionistService/Dockerfile
    ports:
      - "5192:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_ReceptionistDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-receptionist

  results-service:
    build: 
      context: .
      dockerfile: services/ResultsService/Dockerfile
    ports:
      - "5193:80"
    secrets:
      - mongodb_uri
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:80"
      MongoSettings__DatabaseName: "InnoClinic_ResultsDb"
      MongoSettings__ConnectionString: /run/secrets/mongodb_uri
      AuthService__BaseUrl: "http://localhost:5184"
    depends_on:
      - sqlserver-results

  services-service:
    build: 
      context: .
      dockerfile: services/ServicesService/Dockerfile
    ports:
      - "5194:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_ServicesDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-services

  specialization-service:
    build: 
      context: .
      dockerfile: services/SpecializationsService/Dockerfile
    ports:
      - "5195:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=InnoClinic_SpecsDb;User Id=sa;Password=MyPassword12345!;TrustServerCertificate=true;
      - AuthService__BaseUrl=http://localhost:5184
    depends_on:
      - sqlserver-specialization

volumes:
  sqlserver-auth-data:
  sqlserver-account-data:
  sqlserver-appointment-data:
  sqlserver-categories-data:
  sqlserver-doctor-data:
  sqlserver-documents-data:
  sqlserver-office-data:
  sqlserver-patient-data:
  sqlserver-photo-data:
  sqlserver-receptionist-data:
  # sqlserver-results-data:
  sqlserver-services-data:
  sqlserver-specialization-data:

secrets:
  mongodb_uri:
    external: true
