version: '3.8'

services:
  auth-service:
    build: .
    ports:
      - "5184:5184"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5184
      - ConnectionStrings__DefaultConnection=Server=db;Database=InnoClinic_AuthDb;User Id=sa;Password=kN%49!wF;TrustServerCertificate=true;
      - Jwt__Key=q5hTNs7DFIYcx7PbIae6BLInYyFj+zBPwRwQnS5jQbF7H7kncV0X+ZcT6LJvzzQzI5ue/4CkXyAQ3jv4W5EyEw==
      - Jwt__Issuer=InnoClinic.AuthService
      - Jwt__Audience=InnoClinic.Services
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - SA_PASSWORD=kN%49!wF
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "kN%49!wF" -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

volumes:
  sql_data:
